name: "Dokku Deploy action"
author: "Mike Grant"
description: "Deploy to a dokku instance using Github actions"
branding:
  icon: "upload-cloud"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"